VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITableDefineCreator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function writeForTable(ByRef Table As Table, ByVal filePath As String, isAppend As Boolean)

End Function

Public Function writeForConstraints(ByRef Table As Table, ByVal filePath As String, isAppend As Boolean)

End Function


